---
title: "Spatial Viz"
---
```{r}
library(tidyverse)

library(rnaturalearth)
```

```{r}
cma_boundaries <- ne_states(
  country = c("canada", "mexico", "united states of america"),
  returnclass = "sf")
```

```{r}
starbucks <- read.csv("https://mac-stat.github.io/data/starbucks.csv")

starbucks_cma <- starbucks |> 
  filter(Country %in% c('CA', 'MX', 'US'))
```


```{r}

#| fig-alt: "Density of Starbucks in North America"


ggplot(cma_boundaries) + 
  geom_sf() + 
  geom_density_2d(
    data = starbucks_cma,
    aes(x = Longitude, y = Latitude),
    size = 0.2,
    color = "darkgreen"
  ) +
  coord_sf(xlim = c(-179.14, -50), ylim = c(14.54, 83.11)) +
  labs(
    title = "Density of Starbucks in North America",
    caption = "Concentration of starbucks stores in North America"
  ) +
  scale_fill_viridis_c()
```

Use this file to generate a professional looking **spatial** visualization.  The visualization will not perfect the first time but you are expected to improve on it throughout the semester especially after covering advanced topics such as effective viz.
